#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III

## Config - Gap
bspc config window_gap          0
bspc config gapless_monocle     true

## Config - Focus
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

## Config - Window
bspc config split_ratio           0.5

## Config - Border
bspc config borderless_monocle    	true
bspc config border_width        	1
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

### Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome-stable
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Onboard state=floating sticky=on

#
# Autostart
#

# Disable screen blanking.
xset s off
xset s noblank
xset -dpms
xset dpms 0 0 0

# Set brightness to max value on both monitors.
xrandr --output HDMI1 --brightness 1.0 --output eDP1 --brightness 1.0

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Set a scaled random wallpaper
feh --no-fehbg --bg-scale --randomize ~/Documents/Media/Images/wpapers/main_desktop/*

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Picom
# picom -b &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# Notify that restart is completed
dunstify "BSPWM Restarted"

